stages:
  - build

variables:
  AGENT_NAME: "gmail-classifier"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "/certs/client"

build_image:
  stage: build
  image: docker-registry.gitlab.myteksi.net/library/docker:latest
  services:
    - name: docker-registry.gitlab.myteksi.net/library/docker:dind
      alias: docker
  before_script:
    - apk add --no-cache curl bash aws-cli jq python3 openssl
  script:
    - aws ecr get-login-password --region "${ECR_REGION}" | docker login --username AWS --password-stdin "${ECR_REGISTRY}"
    - docker build -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest" -f Dockerfile .
    - docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
  only:
    - master
