apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gmail-classifier
  namespace: dispute-tools
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gmail-classifier
                port:
                  number: 80
